name: Debug Build

on:
  push:
    branches:
      - 'master'
      - 'AppManager-*'
    paths-ignore:
      - 'fastlane/**'
      - 'scripts/**'
      - '*.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'fastlane/**'
      - 'scripts/**'
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleDebug
      - name: Upload build Debug
        uses: actions/upload-artifact@v2
        with:
         name: outputs
         path: app/build/outputs/
